	variable "env" {}
	variable "alb_type" {}
	variable "internal" {}
	variable "vpc_id" {}
	variable "alb_sg_allow_cidr" {}
	variable "subnets" {}
 	variable "port" {}
    variable "protocol" {}
    variable "ssl_policy" {}
    variable "certificate_arn" {}